### ISSUE TITLE
Consider using a custom trait with a blanket impl for Default types instead of requiring Default

### ISSUE THREAD

**Issue by Shnatsel** [Lokathor/tinyvec#71] opened 2020-04-01 12:41 UTC
[It has been pointed out](https://www.reddit.com/r/rust/comments/fshuhk/introducing_tinyvec_100_safe_alternative_to/fm3alig/) that sometimes you want to have a TinyVec of values for which it's easy to produce a valid representation, but `Default` implementation does not make sense. This includes `NonZeroU8` as well as custom structs in some crates, e.g. [in librsvg](https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/318/diffs).

It should be possible to support these via creating a custom trait with a blanket implementation for `T: Default` types as well as implementations for std types such as `NonZeroU8`.

**Comment by Lokathor** [comment] 2020-04-01 17:40
This would be a big upset to the crate and it seems like a duplicate of the OptionVec idea.

**Comment by Shnatsel** [comment] 2020-04-01 19:16
OptionVec would still involve extra overhead, while this approach would extend the list of supported types without any runtime cost.

**Comment by Lokathor** [comment] 2020-04-01 19:41
uuuuuggggghhhhhhh

**Comment by Lokathor** [comment] 2020-04-01 20:10
So really all this enables is standard library types that don't have Default, since any type outside the standard library can have Default, because if it has Sentinel (to pick a name) but not Default then that effectively becomes a weird version of default.

Which is not to say that we can't do it but just that for example `librsvg` and other non-std crates are a bad example of a potential use.

**Comment by Shnatsel** [comment] 2020-04-01 20:18
[People have described hypothetical but plausible scenarios](https://www.reddit.com/r/rust/comments/fshuhk/introducing_tinyvec_100_safe_alternative_to/fm3y9gu/) where you want to put things in a TinyVec but don't want them to implement `Default` because there's no sane default value, but I'm yet to encounter this in practice.

**Comment by Lokathor** [comment] 2020-04-01 20:25
Right but if you have a trait for making inactive values, like this,

```rust
pub trait Sentinel {
  fn sentinel() -> Self;
}
```

Then that's just default under another name, and can still give you bugs. Any way for this crate to make safe placeholder values can be misused by everyone else as well.

**Comment by paulocsanz** [comment] 2020-04-02 01:16
The point is avoiding UB, it just needs to be a SafeUninitialized value. It wont ever be used but the compiler will not get crazy over it while supporting every type without needing a newtype wrapper.

**Comment by Lokathor** [comment] 2020-04-02 04:22
But there is absolutely no way to make the Sentinel trait not ever be used by others. You can't make a trait impl be used by only one other crate and no one else, so anyone can still _also_ make sentinel values whenever they want. So it's just as "bug prone" as having Default. So you might as well impl default on the type.

So the only types that this would actually make a difference for are std types that lack default, which is a few I'll admit, but it isn't that many.

I'm not against the idea, but people should realize that it fixes a lot less than you seem to think it does.

**Comment by Lej77** [comment] 2020-04-02 05:00
Couldn't the trait take a marker type that has a private constructors as an argument? Then only the library could call the trait method. Something like:

```rust
use core::marker::PhantomData;

/// A sentinal marker that is unique to a certain trait implementation.
pub struct SentinelMarker<T> {
    phantom: PhantomData<fn() -> T>,
}

pub trait Sentinel: Sized {
    /// The provided marker can only be constructed from the library and it
    /// is unique to this trait implementation so it can't have been called
    /// from a different trait implementation.
    fn sentinel(marker: SentinelMarker<Self>) -> Self;
}

/// Only functions that are in this module can construct a [`SentinelMarker`]
/// and therefore call the `Sentinel` trait.
pub fn use_sentinel_privately<T: Sentinel>() {
    let _sentinel = T::sentinel(SentinelMarker {
        phantom: PhantomData,
    });
}
```

Don't know if that `Sized` bound is inconvenient and if it could be removed. Also don't know if this is a good idea at all, but thought I would mention it.

**Comment by Lokathor** [comment] 2020-04-02 05:10
Iiiiiinteresting!

**Comment by paulocsanz** [comment] 2020-04-02 07:05
Locking it is not a good idea because it locks other types.

The point is making the API clear that it's a valid value although not necessarily useful.

Why is it a problem if someone uses it, it won't cause any bug that a `Default` wouldn't cause.

Call it `SafeUninitialized` or like `ValidButUseless`. But using `Default` is just asking for problems, there are a bunch of reasons not to implement `Default` for a type, but that can have some garbage value that does not cause UB to be there.

**Comment by Lokathor** [comment] 2020-04-22 18:52
On thinking about it again, a user could still get their hands on the placeholder values, such as with `ArrayVec::set_len` (which is safe in this crate).

I'll make a PR that puts this in and we can have a look

**Comment by le-jzr** [comment] 2020-05-21 21:53
To add my experience to the pile, I'm using TinyVec to store numerical IDs (represented as usize newtypes), for which default value is completely meaningless, same way it would be meaningless to have "a default pointer". I implement `Default` by setting it to `usize::MAX`, which is adequate, but really painful to look at.

IMO the trait should be a custom one, not to prevent misuse, but to avoid squatting within a type whose intended use is something completely different. To point out an example, standard library has the type `Option<T>`, even though `Result<T, ()>` technically achieves the same thing. They are different types because they mean different things, and meaning is what types are for.

**Comment by Lokathor** [comment] 2020-06-18 15:31
After doing up the PR of what this would look like when implemented, it seemed to overall add complexity for the user and very little practical value for the user.

The heart of the issue is that even with a placeholder trait instead of using Default, the placeholder values still have to be 100% safe to create at any time and it must be allowed and safe to either "escape" them out of the vec (in one of several ways) or to let them drop.

Also, to provide good usability, the Placeholder trait would have to be defined with a blanket impl for all things with Default, so users would only really be able to use Placeholder with something that needs to go into these vecs but can't be Default.

I'd be willing to revisit this some day once Rust has stable Specialization, but until then I think this is a path that `tinyvec` isn't going to go down.

**Closed by Lokathor** 2020-06-18 15:31 UTC
Labels: BLOCKS 1.0
